/**
 * This file was automatically generated by scripts/generate-event-types.ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema files and run the generation script.
 */

export interface TelemetryEnvelope {
  id: string;
  eventType: "PageView" | "SessionStart" | "SessionHeartbeat" | "SessionEnd" | "MatchJoin" | "MatchLeave" | "MatchStart" | "MatchEnd" | "UiImpression" | "UiClick" | "UiScrollDepth";
  userId?: string | null;
  timestamp: string;
  payload: PageViewPayload | SessionStartPayload | SessionHeartbeatPayload | SessionEndPayload | MatchJoinPayload | MatchLeavePayload | MatchStartPayload | MatchEndPayload | UiImpressionPayload | UiClickPayload | UiScrollDepthPayload;
}

export interface PageViewPayload {
  url?: string;
  referrer?: string;
  title?: string;
  fromRoute?: string | null;
  toRoute: string;
  guestId?: string | null;
  deviceType: string;
}

export interface SessionStartPayload {
  userAgent: string;
  language?: string;
  screenResolution?: string;
}

export interface SessionHeartbeatPayload {
  state: string;
}

export interface SessionEndPayload {
  durationSeconds: number;
  idleSeconds: number;
  usefulSeconds: number;
}

export interface MatchJoinPayload {
  roomId: string;
  mapId: string;
  mode?: string;
}

export interface MatchLeavePayload {
  roomId: string;
  mapId: string;
  durationSeconds: number;
  reason?: string;
}

export interface MatchStartPayload {
  roomId: string;
  mapId?: string | null;
  gameMode: string;
}

export interface MatchEndPayload {
  roomId: string;
  mapId?: string | null;
  durationSeconds: number;
  winningTeam?: string | null;
}

export interface UiImpressionPayload {
  elementId: string;
  elementType: string;
  visibleTimeMs: number;
}

export interface UiClickPayload {
  elementId: string;
  elementType: string;
  action: string;
}

export interface UiScrollDepthPayload {
  page: string;
  maxDepthPercent: number;
}
