/**
 * This file was automatically generated by scripts/generate-event-types.ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema files and run the generation script.
 */

export interface TelemetryEnvelope {
  id: string;
  eventType: "PageView" | "SessionStart" | "MatchJoin" | "MatchLeave";
  userId?: string | null;
  timestamp: string;
  payload: PageViewPayload | SessionStartPayload | MatchJoinPayload | MatchLeavePayload;
}

export interface PageViewPayload {
  url: string;
  referrer?: string;
  title?: string;
}

export interface SessionStartPayload {
  userAgent: string;
  language?: string;
  screenResolution?: string;
}

export interface MatchJoinPayload {
  roomId: string;
  mapId: string;
  mode?: string;
}

export interface MatchLeavePayload {
  roomId: string;
  mapId: string;
  durationSeconds: number;
  reason?: string;
}
