version: '3.8'

services:
  game-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"        # Host port 80 maps to the internal react/vite (serve) at 3000
      - "8080:8080"      # Backend WebSocket maps directly 8080 to 8080
    container_name: threejs-game-app
    restart: unless-stopped
