import fs from "node:fs";
import path from "node:path";

function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function parseProperties(properties: any, required: string[]): string {
  let result = "";
  for (const [key, prop] of Object.entries<any>(properties)) {
    const isRequired = required.includes(key);
    let typeStr = "any";
    const actualTypes = Array.isArray(prop.type) ? prop.type : [prop.type];
    const mappedTypes: string[] = [];

    for (const t of actualTypes) {
      if (t === "integer" || t === "number") {
        mappedTypes.push("number");
      } else if (t === "string") {
        mappedTypes.push("string");
      } else if (t === "boolean") {
        mappedTypes.push("boolean");
      } else if (t === "array") {
        mappedTypes.push("any[]");
      } else if (t === "object") {
        mappedTypes.push("Record<string, any>");
      } else if (t === "null") {
        mappedTypes.push("null");
      }
    }

    if (mappedTypes.length > 0) {
      typeStr = mappedTypes.join(" | ");
    }
    result += `  ${key}${isRequired ? "" : "?"}: ${typeStr};\n`;
  }
  return result;
}

function generatePayloadInterface(name: string, schema: any): string {
  const capName = capitalizeFirst(name);
  return `export interface ${capName}Payload {\n${parseProperties(schema.properties, schema.required || [])}}`;
}

function main() {
  console.log("Generating TypeScript types from JSON Schemas...");

  const schemasDir = path.join(process.cwd(), "server/analytics/schemas");
  const outputFilePath = path.join(process.cwd(), "server/analytics/types.ts");

  const pageViewSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "pageView.json"), "utf8"));
  const sessionStartSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "sessionStart.json"), "utf8"));
  const sessionHeartbeatSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "sessionHeartbeat.json"), "utf8"));
  const sessionEndSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "sessionEnd.json"), "utf8"));
  const matchJoinSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "matchJoin.json"), "utf8"));
  const matchLeaveSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "matchLeave.json"), "utf8"));
  const matchStartSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "matchStart.json"), "utf8"));
  const matchEndSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "matchEnd.json"), "utf8"));
  const uiImpressionSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "uiImpression.json"), "utf8"));
  const uiClickSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "uiClick.json"), "utf8"));
  const uiScrollDepthSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "uiScrollDepth.json"), "utf8"));
  const editorSessionSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "editorSession.json"), "utf8"));
  const editorActionSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "editorAction.json"), "utf8"));
  const mapStateTransitionSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "mapStateTransition.json"), "utf8"));

  const pageViewTypes = generatePayloadInterface("pageView", pageViewSchema);
  const sessionStartTypes = generatePayloadInterface("sessionStart", sessionStartSchema);
  const sessionHeartbeatTypes = generatePayloadInterface("sessionHeartbeat", sessionHeartbeatSchema);
  const sessionEndTypes = generatePayloadInterface("sessionEnd", sessionEndSchema);
  const matchJoinTypes = generatePayloadInterface("matchJoin", matchJoinSchema);
  const matchLeaveTypes = generatePayloadInterface("matchLeave", matchLeaveSchema);
  const matchStartTypes = generatePayloadInterface("matchStart", matchStartSchema);
  const matchEndTypes = generatePayloadInterface("matchEnd", matchEndSchema);
  const uiImpressionTypes = generatePayloadInterface("uiImpression", uiImpressionSchema);
  const uiClickTypes = generatePayloadInterface("uiClick", uiClickSchema);
  const uiScrollDepthTypes = generatePayloadInterface("uiScrollDepth", uiScrollDepthSchema);
  const editorSessionTypes = generatePayloadInterface("editorSession", editorSessionSchema);
  const editorActionTypes = generatePayloadInterface("editorAction", editorActionSchema);
  const mapStateTransitionTypes = generatePayloadInterface("mapStateTransition", mapStateTransitionSchema);

  const fileContent = `/**
 * This file was automatically generated by scripts/generate-event-types.ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema files and run the generation script.
 */

export interface TelemetryEnvelope {
  id: string;
  eventType: "PageView" | "SessionStart" | "SessionHeartbeat" | "SessionEnd" | "MatchJoin" | "MatchLeave" | "MatchStart" | "MatchEnd" | "UiImpression" | "UiClick" | "UiScrollDepth";
  userId?: string | null;
  timestamp: string;
  payload: PageViewPayload | SessionStartPayload | SessionHeartbeatPayload | SessionEndPayload | MatchJoinPayload | MatchLeavePayload | MatchStartPayload | MatchEndPayload | UiImpressionPayload | UiClickPayload | UiScrollDepthPayload;
}

${pageViewTypes}

${sessionStartTypes}

${sessionHeartbeatTypes}

${sessionEndTypes}

${matchJoinTypes}

${matchLeaveTypes}

${matchStartTypes}

${matchEndTypes}

${uiImpressionTypes}

${uiClickTypes}

${uiScrollDepthTypes}
`;

  fs.writeFileSync(outputFilePath, fileContent, "utf8");
  console.log(`Successfully generated types in: ${outputFilePath}`);
}

main();
