import fs from "node:fs";
import path from "node:path";

function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function parseProperties(properties: any, required: string[]): string {
  let result = "";
  for (const [key, prop] of Object.entries<any>(properties)) {
    const isRequired = required.includes(key);
    let typeStr = "any";
    if (prop.type === "integer" || prop.type === "number") {
      typeStr = "number";
    } else if (prop.type === "string") {
      typeStr = "string";
    } else if (prop.type === "boolean") {
      typeStr = "boolean";
    } else if (prop.type === "array") {
      typeStr = "any[]";
    } else if (prop.type === "object") {
      typeStr = "Record<string, any>";
    }
    result += `  ${key}${isRequired ? "" : "?"}: ${typeStr};\n`;
  }
  return result;
}

function generatePayloadInterface(name: string, schema: any): string {
  const capName = capitalizeFirst(name);
  return `export interface ${capName}Payload {\n${parseProperties(schema.properties, schema.required || [])}}`;
}

function main() {
  console.log("Generating TypeScript types from JSON Schemas...");

  const schemasDir = path.join(process.cwd(), "server/analytics/schemas");
  const outputFilePath = path.join(process.cwd(), "server/analytics/types.ts");

  const pageViewSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "pageView.json"), "utf8"));
  const sessionStartSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "sessionStart.json"), "utf8"));
  const matchJoinSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "matchJoin.json"), "utf8"));
  const matchLeaveSchema = JSON.parse(fs.readFileSync(path.join(schemasDir, "matchLeave.json"), "utf8"));

  const pageViewTypes = generatePayloadInterface("pageView", pageViewSchema);
  const sessionStartTypes = generatePayloadInterface("sessionStart", sessionStartSchema);
  const matchJoinTypes = generatePayloadInterface("matchJoin", matchJoinSchema);
  const matchLeaveTypes = generatePayloadInterface("matchLeave", matchLeaveSchema);

  const fileContent = `/**
 * This file was automatically generated by scripts/generate-event-types.ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema files and run the generation script.
 */

export interface TelemetryEnvelope {
  id: string;
  eventType: "PageView" | "SessionStart" | "MatchJoin" | "MatchLeave";
  userId?: string | null;
  timestamp: string;
  payload: PageViewPayload | SessionStartPayload | MatchJoinPayload | MatchLeavePayload;
}

${pageViewTypes}

${sessionStartTypes}

${matchJoinTypes}

${matchLeaveTypes}
`;

  fs.writeFileSync(outputFilePath, fileContent, "utf8");
  console.log(`Successfully generated types in: ${outputFilePath}`);
}

main();
